name: Sample Github Actions On GAE CI Development

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy Development
    runs-on: ubuntu-latest
    environment:
      name: dev

    env:
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GAE App Deploy Dev
        run: |
          echo "$GCLOUD_SERVICE_KEY"  | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project "$GCLOUD_PROJECT_ID"
          gcloud --quiet app deploy
