name: Sample Github Actions On GAE CI

on: [ push ]
# on:
  # push:
    # tags:
    #   - 'v*'
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GAE Deploy
        run: |
          echo "$GCLOUD_SERVICE_KEY"  | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project "$GCLOUD_PROJECT_ID"
          gcloud --quiet app deploy
