name: Sample Github Actions On GAE CI/CD Development

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm ci, build sass
        run: |
          npm ci
          npm run scss
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            app.yaml
            www
            !www/scss/**/**.scss

  deploy:
    name: Deploy
    needs: build

    runs-on: ubuntu-latest
    environment:
      name: dev

    env:
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: GAE App Deploy Dev
        run: |
          echo "$GCLOUD_SERVICE_KEY"  | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project "$GCLOUD_PROJECT_ID"
          gcloud --quiet app deploy
