name: Sample Github Actions On GAE CI

on: [ push ]
# on:
  # push:
    # tags:
    #   - 'v*'
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GAE_DEPLOY_KEY: ${{ secrets.GAE_DEPLOY_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: GAE Deploy
        run: |
          echo 'github-actions@sample-github-actions.iam.gserviceaccount.com' | gcloud auth activate-service-account --key-file "$GAE_DEPLOY_KEY"
          gcloud app deploy app.yaml --project sample-github-actions
